Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"
    - "db/**"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "db/**"
    - "config/routes.rb"
    - "app/views/plans/show.json.jbuilder"
    - "app/controllers/plans_controller.rb"

Metrics/MethodLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "db/**"
    - "app/controllers/plans_controller.rb"
    - "app/views/plans/show.json.jbuilder"

Metrics/LineLength:
  Max: 140
Documentation:
    Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false
