version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    working_directory: ~/api
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-cache-{{ checksum "Gemfile.lock" }}
          - v1-cache-

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run: sudo apt install postgresql-client

      - save_cache:
          paths:
            - vendor/bundle
          key: v1-cache-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:reset
      - run: bundle exec rspec --format RspecJunitFormatter --out rspec/rspec.xml
      - run: bundle exec rubocop -R

      - store_test_results:
          path: rspec/
      - store_artifacts:
          path: rspec/
          destination: rspec
      - store_artifacts:
          path: ./coverage
          destination: coverage
  deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/api
    steps:
      - checkout
      - run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: bash .circleci/setup-heroku.sh $CIRCLE_BRANCH
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Deploy to Heroku
          command: git push heroku $CIRCLE_BRANCH:master
      - run:
          name: Migrations
          command: heroku run rake db:migrate

workflows:
  version: 2
  workflow:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only:
                  - master
                  - dev
