default: &default
  adapter: postgresql
  encoding: utf8
  database: iic2113_api_development
  pool: 5

development:
  <<: *default
  database: iic2113_api_development

test:
  <<: *default
  database: iic2113_api_test

production:
  <<: *default
  database: iic2113_api_production
