Rails.application.routes.draw do
  resources :comunicates
  resources :satisfactions
  resources :surveys
  resources :suggestions
  resources :questions
  resources :evaluations
  resources :blogs
  resources :implements
  resources :diffusions
  resources :selection_plans
  resources :others
  resources :resources
  resources :places
  resources :members
  resources :plans
  resources :selections
  resources :methoods
  resources :experiences
  resources :users
end
