# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cae9ef2561762c29e5635ec03054b662ca76d16aa1407f2b302e93667f38c96684175b9f6ecac4a39c6e184e0560ab84cf9d0d352f252ad2cd495cfc8a1ec5de

test:
  secret_key_base: 3e7b87b44d507ac2dd11cc9245e0b59a64d88a23a248b2e1b1277cd21811bbcd2cdc1d0f3fa80a0eb920fe76b8c0fa1815e849ce2f48208f37feb23f3d8640ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
